# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-22-04
- name: Deply monitoring
  hosts: servers # Which host to apply, you can replace by `servers`, or by `servers_1, servers_2` for multiple groups
  become: yes # To run commands as a superuser (e.g., sudo)
  vars:
    default_container_name: datalake-minio
    default_container_image: minio/minio
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install prerequisites
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - vim
          - openjdk-11-jre-headless
        state: latest
        update_cache: true
    
    # - name: map python3 to python
    #   command: ln -s /usr/bin/python3 /usr/bin/python

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Update apt and install docker-ce
      pip:
        name: docker
        version: 6.1.3

    - name: Pull the Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Copy prometheus config to server
      synchronize:
        src: prometheus
        dest: /home/luongphambao
        recursive: yes
        archive: yes
        delete: yes
        compress: yes
      become: yes
    - name: Copy grafana config to server
      synchronize:
        src: grafana
        dest: /home/luongphambao
        recursive: yes
        archive: yes
        delete: yes
        compress: yes
      become: yes
    
    - name: Copy monitoring docker compose file to server
      copy:
        src: prom-graf-docker-compose.yaml
        dest: /home/luongphambao
        mode: preserve


    - name: Install multiple packages
      ansible.builtin.pip:
        name: 
          - pandas 
          - docker-compose
    # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
    - name: Start Docker containers
      community.docker.docker_compose:
        project_src: /home/luongphambao
        files: prom-graf-docker-compose.yaml

    
