version: '3.8'
services:
  postgresql:
    image: postgres:13
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=helen
      - POSTGRES_USER=helen
      - POSTGRES_PASSWORD=helen
    volumes: 
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
    driver: local