version: '2'
services: 
  postgresql: 
    image: debezium/postgres:13
    platform: linux/amd64 
    container_name: postgresql 
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_DB=helen 
      - POSRRGES_USER=helen
      - POSTGRES_PASSWORD=helen 
    volumes: 
      - dbt_postgresql_data:/var/lib/postgresql/data

volumes: 
  dbt_postgresql_data: 
    driver: local 