dbt_nyc:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: helen
      pass: helen
      database: helen
      schema: public
    prod:
      type: postgres
      host: localhost
      port: 5432
      user: helen
      pass: helen
      database: helen
      schema: public